// tests/test-database-url.test.ts
import { describe, expect, it } from 'vitest'
import { assertTestDatabaseUrl } from '@/tests/test-database-url.mjs'

const databaseName = 'auth_todo_test_00000000000000000000000000000000'
const testUrl = `postgresql://postgres@127.0.0.1:54321/${databaseName}`

describe('integration database guard', () => {
  it('accepts the temporary database URL generated by the runner', () => {
    expect(assertTestDatabaseUrl(testUrl)).toBe(testUrl)
  })

  it.each([
    undefined,
    '',
    'not-a-url',
    'postgresql://postgres@127.0.0.1:54321/auth_todo',
    `postgresql://postgres@database.example.com:54321/${databaseName}`,
    `postgresql://postgres@127.0.0.1/${databaseName}`,
    `postgresql://other@127.0.0.1:54321/${databaseName}`,
    `${testUrl}?host=database.example.com`,
    `${testUrl}#fragment`,
    `postgresql://postgres:password@127.0.0.1:54321/${databaseName}`,
    'postgresql://postgres@127.0.0.1:54321/auth_todo_test_manual',
    `https://postgres@127.0.0.1:54321/${databaseName}`,
  ])('rejects missing or non-temporary database configuration: %j', (value) => {
    expect(() => assertTestDatabaseUrl(value)).toThrow()
  })
})
