// app/layout.tsx
import { GeistMono } from 'geist/font/mono'
import { GeistSans } from 'geist/font/sans'
import type { Metadata } from 'next'
import { AuthGuard } from '@/components/auth-guard'
import { ThemeProvider } from '@/components/theme-provider'
import { Toaster } from '@/components/ui/sonner'
import { cn } from '@/lib/utils'
import './globals.css'

export const metadata: Metadata = {
  title: 'To-Do',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="h-full antialiased" suppressHydrationWarning>
      <body className={cn('flex', 'min-h-full', GeistSans.className, GeistSans.variable, GeistMono.variable)}>
        <ThemeProvider defaultTheme="system">
          <AuthGuard>{children}</AuthGuard>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  )
}
